spatie/laravel-translatable

- src/HasTranslations.php
Funky syntax, not sure if it's the way to go.
If the `$key` field exists biut is empty, an empty string will be json decoded making the function return null and crashing. We need to do a check if the key is set and isn't empty.
> Some added type safety to getTranslations

- src/HasTranslations.php
- tests/TranslatableTest.php
I stumbled upon the case where I need to check if an attribute is translatable, e.g.:
```php
$attribute = 'name'; // Defined elsewhere dynamically.
if ($model->isTranslatableAttribute($attribute)) {
// Do something here...
}
```
I can do the check manually using `getTranslatedAttributes()` but in the end I'd just have a copy of `isTranslatableAttribute()`... So let's expose it..
> Make isTranslatableAttribute() public

- README.md
The ';' after the functions will fail the next line of code, which expects a NewsItem object.
> Some php code what will fail when you copy it

- CHANGELOG.md
- README.md
- src/HasTranslations.php
- tests/TranslatableTest.php
I reused some of bbrother's code from the PR #21 to realize the possibility to set translations with the default eloquent syntax (`$model->key = 'Translation';`) without using magic methods.
If a user sets a translation this way, the current app locale is used to save the translation (as it is already the case for getting translations).
> Support for setting a translation directly through the property

- src/Events/TranslationHasBeenSet.php
On the `TranslationHasBeenSet` event the actual `$key` was never set due to an invalid attribute name in the constructor.
> Fix event attribute name

- src/HasTranslations.php
- tests/TranslatableTest.php
In addition to my previous PR on mutators, I was thinking about this feature request.
Sometimes, when I set a field using a mutator, I need to use another field in this mutator. But if this another field is also a translatable field, it does not works as expected.
I wrote a test to generally explain that. But here's a "real world" example :
```php
class BlogPost extends Model
{
use HasTranslations;
protected $translatable = ['title', 'slug'];
public function setSlugAttribute($slug, $locale = 'en')
{
if (!$slug) {
$slug = $this->getTranslation('title', $locale);
}
$this->attributes['slug'] = str_slug($slug);
}
}
```
Given the name is set to something like `['en' => 'Hello world', 'fr' => 'Bonjour le monde']` and the slug is null, then the slug will be set to `['en' => 'hello-world', 'fr' …
> It can translate a field based on the translations of another one

- src/HasTranslations.php
This would allow for better extensibility in other packages. An example I'm having in mind, is [Backpack's HasTranslations trait](https://github.com/Laravel-Backpack/CRUD/blob/master/src/ModelTraits/SpatieTranslatable/HasTranslations.php).
> Replace config('app.locale') with getLocale()

- src/HasTranslations.php
- tests/TranslatableTest.php
I had to create migration to add json not null columns to a table.
After that all values are set to `null` which is valid json, so after decoding it value was null, but array was expected.
This is just handling that situation.
> Handle when json field is encoded null

- README.md
- src/HasTranslations.php
- tests/TranslatableTest.php
Added a method called `getAllTranslations` to return every translatable field and the possible values. This is valuable because when creating a UI to edit translations, having each language and all it's values returned at the same time is much easier to deal with than looping and requesting each attribute/key and language that's being used.
> Add getAllTranslations()

- src/HasTranslations.php
This is required to get the Nova tool working. The name is way too generic though. I say we either use a more "technical" name, or release a new major version. Maybe revisit some other things while we're at it?
> Add getTranslationsAttribute accessor

- src/HasTranslations.php
- tests/TranslatableTest.php
Why I think this should be merged:
I've a form with 4 input fields:
```
<input type="text" name="name[nl]">
<input type="text" name="name[en]">
<input type="text" name="name[de]">
<input type="text" name="name[fr]">
```
When I submit the form and won't fill the English translation it will be saved like this in the DB:
```
{"de": "DE", "en": null, "fr": "FR", "nl": "NL"}
```
So when I change the locale to English I'm not getting anything because it's null. It should fallback to the fallback locale (in my case NL) because I've set so.
In this PR I'm filtering out those empty translations so the fallback is working.
> Filter empty/null translations

- src/HasTranslations.php
In short:
- in version 2.x, ```getTranslation()``` could return an array/object;
- in version 3.x, the result for ```getTranslation()``` must be an array;
**Removing this constraint allows developers to use this package for translating non-text attributes**. It fixes the only breaking change I've encountered when moving from 2.x to 3.x, while breaking _nothing_ in the current version.
Even if you did not intend for developers to use your package to translate non-text attributes, I'd say forcing the result to ```array``` brings no value. While removing it allow _some_ developers to keep using your package, to translate strings, arrays, objects, whatever they want.
What do you think - too strict of a constraint here?
PS. This issue was also mentioned by @promatik in …
> [Fixed breaking change] Added support for translating non-text attributes

- src/HasTranslations.php
- tests/TranslatableTest.php
This is a fix for #143.
All values that PHP evaluates to 'false' were not returned, including 0. This PR will make sure that only empty strings and missing translations are stripped from the result.
As this is my first PR, please let me know if more information is needed.
Thank you.
> Allow 0 to be used a translation value

- composer.json
The provider is no longer required.
Laravel 5.8 is throwing errors while installing this (v4.1) package -
```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
In ProviderRepository.php line 208:
Class 'Spatie\Translatable\TranslatableServiceProvider' not found  
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```
> Fix: Remove the provider

- src/HasTranslations.php
Applicable when trying to set active on one translation, but inactive on another.
> Allow false or true values in translations

- .gitignore
- composer.json
- src/HasTranslations.php
Since I am using this package in a non-laravel-framework environment I don't need to have the whole framework installed.
This PR updates the composer dependencies to only include `illuminate/database` and `illuminate/support`.
I've also had to update the `config()` references since the helper is defined in `illuminate/foundation`.
Additionally I've added the `.phpunit.result.cache` to the `.gitignore` file
Thanks for this handy package 🙂
> Only include required illuminate dependencies

- src/HasTranslations.php
Just realized that alias method `translate()` missed third param for fallback use, so I added it.
> add third param to translate method

- src/Events/TranslationHasBeenSet.php
- src/Exceptions/AttributeIsNotTranslatable.php
This removes the constraint of `Model` to allow for any class that `HasAttributes` to `HasTranslatable` as well.
This opens other use cases such as using laravel-translatable inside `Template` classes with [https://github.com/whitecube/nova-page](nova-page).
Thanks!
> Support HasAttributes, not Model

- src/HasTranslations.php
- tests/TestCase.php
- tests/TestModel.php
- tests/TranslatableTest.php
This PR will fix bugs on using forgetTranslation & forgetAllTranslations methods on models having mutable fields (as raised in #202).
> Fix forgetTranslation & forgetAllTranslations on fields with mutator

- config/translatable.php
Hello,
Since PR #171, the package uses its default value for "fallback_locale" instead of app value.
Should not it be as follows by default ?
```php
return [
'fallback_locale' => null,
];
```
Thanks ;)
> FIX - Use app.fallback_locale by default

- README.md
- src/HasTranslations.php
- tests/TranslatableTest.php
This is an attempt at making this package more elegant / easy to use.
The default locale when using the model accessor is the app locale,
In some cases you might need to get / set translations with a custom locale and if you do so the accessor is not usable without overriding the app locale.
In most cases you could just override the app locale for a short period of time but this feels dirty.
Instead of using the app locale this PR adds a `$locale` property on the trait that is used instead of the app locale when set.
That makes it possible to use the accessor with any locale.
Example:
Imagine you want to save some data with the orm through a method:
Model:
``` php
// Model
class Item extends Model
{
use HasTranslations;
protected $fillable = ['name', 'info', 'state', 'comment'];
public …
```
> [feature] elegant syntax update

- README.md
- src/HasTranslations.php
- tests/TranslatableTest.php
Hi!
In order to allow the users to replace all the translations for  a single key in one go, we add the replaceTranslations function which forgets all the translations for the key provided and registers the new values.
```php
public function replaceTranslations(string $key, array $translations)
```
Here's an example:
```php
$translations = ['en' => 'hello', 'es' => 'hola'];
$newsItem->setTranslations('hello', $translations);
$newsItem->getTranslations(); // ['en' => 'hello', 'es' => 'hola']
$newTranslations = ['en' => 'hello'];
$newsItem->replaceTranslations('hello', $newTranslations);
$newsItem->getTranslations(); // ['en' => 'hello']
```
If something is missing or do you consider that we should change something, please let me know.
> [Feature] add replaceTranslations method

- src/HasTranslations.php
This PR changes the casts for translatable columns to `string`, as discussed in https://github.com/spatie/laravel-translatable/issues/234.
> Use string casting for translatable columns

- README.md
First : thanks for your work , you are Inspiring person for all the community
-------
* I think this part removed by mistake from Readme file 
everything is working fine when dealing with model and retrieving one instance ,
But when use pagination it return json , the first thing is doubt your code and start debugging ,
but after while you search google  and find this https://github.com/spatie/laravel-translatable/issues/74
blease Re-add this part OR solve this convusion .
> Re-add #using-translations-in-json-responses part to Readme file

- .github/workflows/run-tests.yml
- CHANGELOG.md
- README.md
- composer.json
- src/Events/TranslationHasBeenSet.php
- src/Exceptions/AttributeIsNotTranslatable.php
- src/HasTranslations.php
- src/TranslatableServiceProvider.php
This PR adds a new major version, v5.0.0.
Specifically, it:
- Removes support for all PHP 7.x versions.
- Requires PHP 8.0+.
- All syntax converted to PHP 8 where possible.
- Removes Laravel v6 support.
- Implements spatie/laravel-package-tools.
- Fixes some minor Readme issues.
- _Updates the changelog - release date needs to be updated, currently is "unreleased"._
> Add PHP 8-only Support (v5)

- src/HasTranslations.php
I noticed that the `translate` and `getTranslationWithFallback` methods were not updated to return the "mixed" type as per the changes in #269 
I've recently ran into a type error when calling `getTranslationWithFallback` on a Translatable field which has been cast to an `array` on the model.
As `getTranslationWithFallback/translate` return the value that is returned from `getTranslation` the return types should match.
> Fix: return types should match 'mixed' return type of getTranslation

- src/HasTranslations.php
This PR resolves the mentioned issue in #299  by @killgt related to non-string translations value.
> Solve the string value issue in filterTranslations method

- README.md
- config/translatable.php
- src/HasTranslations.php
- tests/TranslatableTest.php
Often models are not fully translated into every needed language. When a field is missing the translation for the preferred user locale and the fallback locale, no text is shown at all.  
This change proposes an option to return the first translation available in the above described condition to enhance user experience.
> Return any translation if neither preferred locale nor fallback locale found

- src/HasTranslations.php
When model hasSetMutator, repopulating $value at setTranslation will not work with json encoded value, as it will treat the value as a string value.
force the value to be retrieved via getTranslations method again to force convert json string into valid arrays.
> Changing the way to populate setTranslation

- src/HasTranslations.php
- tests/TranslatableTest.php
Currently it is not possible to delete all translations of certain attribute while also having the option to save null instead of an empty json string (e.g. `{"en": null, "nl": null}`). This PR adds the `forgotTranslations` method to support this behavior.
The `forgotTranslations` method has 2 parameters:
- the attribute key
- a boolean that allows you to set the attribute to null after forgetting the translations of the attribute
```
$article->forgetTranslations('title'); // 'title' attribute is empty array
$article->forgetTranslations('title', true); // 'title' attribute is null
```
To add this method I had to make a very small change in the `setTranslations` method. If you call that method with an empty array, then the attribute will not be updated/set. To solve this I added an …
> Add 'forgetTranslations' method

- .github/workflows/run-tests.yml
- composer.json
- tests/EventTest.php
- tests/Pest.php
- tests/TestCase.php
- tests/TestSupport/TestModel.php
- tests/TranslatableTest.php
This pull request contains changes for migrating your test suite from PHPUnit to [Pest](https://pestphp.com/) automated by the [Pest Converter](https://laravelshift.com/phpunit-to-pest-converter).
**Before merging**, you need to:
- Checkout the `shift-57946` branch
- Review **all** of the comments below for additional changes
- Run `composer update` to install Pest with your dependencies
- Run `vendor/bin/pest` to verify the conversion
> PHPUnit to Pest Converter

- docs/basic-usage/getting-and-settings-translations.md
There is a typo in documentation example. The attribute name is "name", not "hello". This PR fix it.
> Fix typo in "Getting and setting translations"

- docs/basic-usage/removing-translations.md
The example given did not demonstrate usage of the forgetAllTranslations() method.
> Fixed example for forgetAllTranslations() method.

- src/HasTranslations.php
- tests/TranslatableTest.php
Newly added method: locales returns all locales used by a model so it's easier to check what translations are there.
```php
$model->setTranslation('name', 'en', 'testValue_en');
$model->setTranslation('name', 'fr', 'testValue_fr');
$model->setTranslation('name', 'tr', 'testValue_tr');
$model->save();
$model->refresh()->locales();
// ['en', 'fr', 'tr']
```
> added locales method

- .github/dependabot.yml
- .github/workflows/dependabot-auto-merge.yml
- composer.json
This PR adds dependabot automation for this repository.
This PR adds a dependabot configuration file that enables weekly update checks for all github actions used within workflows in the project.
This PR includes a workflow that automatically merges dependabot PRs for minor and patch version updates (major version bumps must be manually merged to avoid breaking changes, with one exception - see below).
When performing auto-merging of PRs, Github Actions that have a major version update AND a compatibility score of >=90% are automatically merged as way to reduce the manual work of merging PRs that are of no risk of breaking changes. ONLY Github Actions that have a major version update are considered for automatic merging.  Other dependencies are excluded.
Using these features will help …
> Add Dependabot Automation

- README.md
- docs/basic-usage/getting-and-settings-translations.md
- docs/basic-usage/querying-translations.md
- src/HasTranslations.php
- tests/TranslatableTest.php
In some cases, there are times when I want to extract content according to the user's locale, and in this case, I found these solutions instead of constantly writing queries.
`whereLocale` and `whereLocales` methods.
```php
$post->whereLocale('title', 'en')->get();
// or mutliple locales
$post->whereLocales('title', ['en', 'fr'])->get();
```
> Added whereLocale and whereLocales methods

- docs/basic-usage/handling-missing-translations.md
- src/HasTranslations.php
- tests/TestSupport/TestModelWithoutFallback.php
- tests/TranslatableTest.php
In our project we use this package on multiple models. Almost all of them need a fallback language except a new one. We access the attribute using `$model->translatableAttribute` but this always uses the fallback language.
PR adds the possibility to add a `useFallbackLocale` property to the model.
```php
class Article extends Model
{
use HasTranslations;
protected $useFallbackLocale = false;
}
``` 
This was my solution without this PR:
```php
Translatable::fallback(missingKeyCallback: function (
Model $model,
string $translationKey,
string $locale,
string $fallbackTranslation,
string $fallbackLocale,
) {
if ($model instanceof NewsNotification) {
return '';
}
return $fallbackTranslation;
});
```
Feels like a lot of code to disable fallback language.
> Enable fallback locale on a per model basis

- docs/advanced-usage/usage-with-factories.md
- src/TranslatableServiceProvider.php
- tests/TranslatableTest.php
Because factory definitions do not go through a Model's accessors/mutators, old definitions break when migrating columns to use the translatable trait. This PR helps users overcome this hurdle, by adding a macro to the factory that outputs valid JSON for the translatable columns.
This macro enables users to do the following in factory definitions, where `description` is a translatable column:
**Scenario 1:**
```php
return [
'description' => $this->translatable('en', 'English description'),
];
// output: {"en":"English description"}
```
**Scenario 2:**
```php
return [
'description' => $this->translatable(['en', 'nl'], 'English and Dutch description'),
];
// output: {"en":"English and Dutch description","nl":"English and Dutch description"}
```
**Scenario 3:**
```php
return [
'description' …
```
> Add macro for `$this->translations()` in factories

- docs/basic-usage/handling-missing-translations.md
- src/HasTranslations.php
- tests/TestSupport/TestModelWithFallbackLocale.php
- tests/TranslatableTest.php
In a project I'm working on, my models have translatable attributes but also a 'fallback_locale' attribute. If for example the title of the model does not have a translation in the user's current locale, then it should use the translation in the 'fallback_locale' that is set on the model (instead of a global fallback locale that is set for entire application). To support this behavior, this PR adds the option to define a `getFallbackLocale` method on a model
```php
class Article extends Model
{
use HasTranslations;
protected $translatable = [
'title',
];
public function getFallbackLocale() : string
{
return $this->fallback_locale; // a column/attribute on the model
}
}
```
```php
$article->setTranslation('title', 'fr', 'french title');
$article->setTranslation('title', 'en', 'english …
```
> Add getFallbackLocale method

- src/HasTranslations.php
Converting the `whereLocale()` / `whereLocales()` static methods to scopes makes it possible to use them on existing queries instead of being required to use them as the first method
> Convert static methods to scopes

- src/HasTranslations.php
- tests/TranslatableTest.php
Currently, when saving this in the model:
```php
['en' => 'Title', 'nl' => null, 'de' => null]
```
…we have this in database:
```php
['en': 'Title', 'de': null]
```
This pull request fix this strange behavior and the data saved in the database is now:
```php
['en' => 'Title', 'nl' => null, 'de' => null]
```
Note : In the version 3.1.3 of this package, the number of translations where correctly maintained in the database, I don't know exactly when this behavior changed, but it can lead to bugs in some situations.
> Keep the number of translations even with null values

- src/HasTranslations.php
- tests/TranslatableTest.php
Hi 👋
This PR reverts the changes made in the original PR. Even though I am a proponent of the suggested changes, unfortunately it's a breaking change for people who don't make use of type juggling through the use of `declare(strict_types=1)`. 
Moreover, this is also going to break the code of those who are on the most recent PHP versions where `str_*` functions no longer accept `null` as a legitimate value.
The suggested changes should be targeted at a `v7` or a `next` branch, ideally.
Thank you 🙏
> Revert "Keep null value"

- src/HasTranslations.php
German umlauts were not searchable with `whereRaw` and escaped unicodes in the JSON.
> fix: allow raw searchable umlauts

- src/HasTranslations.php
- tests/TranslatableTest.php
Hi,
When using accessors on translatable attributes, the `toArray` method doesn't work like expected.
Normally when you get the value of an attribute, the accessor gets the translated value as its parameter. When using `toArray` on the model the accessor gets the raw value instead.
I've added a test to reproduce the issue.
This change only affects translated attributes with accessors, the `mutateAttributeForArray` method gets called only for attributes with accessors defined.
> Fix toArray when using accessors on translatable attributes

- src/Facades/Translatable.php
Fix fallback method definition that is lacking "void", occasioning code analyzers like PHPStan to fail. This was recently introduced [here](https://github.com/spatie/laravel-translatable/pull/438).
The previous PHPdoc is not a valid php-doc comment and causes issues on, for example, PHPStan when analyzing the code:
> fix: PHPDoc block in Translatable facade

- README.md
- src/HasTranslations.php
- tests/TranslatableTest.php
Hi,
I've added ability to choose operand for where clause in json scopes. For example:
```php
$query->whereJsonContainsLocale('title', 'en', 'hello%', 'like');
```
> Added operand for json scopes

- src/HasTranslations.php
- src/Translatable.php
This commit fixes the issue by adding nullable types to the method signatures. https://github.com/php/php-src/blob/php-8.4.0RC1/UPGRADING#L497
4. Deprecated Functionality
- Core: . Implicitly nullable parameter types are now deprecated. RFC: https://wiki.php.net/rfc/deprecate-implicitly-nullable-types
> PHP 8.4 deprecates implicitly nullable parameter types.

- src/HasTranslations.php
- src/Translatable.php
- tests/TranslatableTest.php
This pull request introduces configuration options to control how null and empty string values are handled in translations. It also handles a case where the column value is `null` it returns `null` instead of empty string.
- Pull request #427 introduced a change that allowed expecting null values where previously it would return an unexpected value. This was a positive change for future development.
- However, this caused issues for existing production deployments where code relied on the previous behavior.
- Pull request #428 reverted the changes introduced in #427.
This pull request provides a solution that addresses both scenarios:
- Maintains the default behavior of the library.
- Introduces a configuration option to allow developers to explicitly return null and empty strings where …
> Allow configuration for handling null and empty strings in translations (Fixes #456)

- src/HasTranslations.php
- tests/TranslatableTest.php
Hi,
Since the latest version, attribute mutators of translated attributes are getting called twice when getting the translated value.
It is happening because the following change in PR #465 in the `getTranslation` method:
```php
// if column value is `null` then we have nothing to do, return `null`
if (is_null(parent::getAttributeValue($key))) {
return null;
}
```
`parent::getAttributeValue` will try to transform the value using the attribute, which causes it to be called with the raw value stored in the database.
It wouldn't be a big issue but in my case I have a translated date which I'd like to parse into Carbon.
For example:
```php
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;
class …
```
> Fix attribute mutators

- src/HasTranslations.php
- tests/TranslatableTest.php
This PR enhances the `setAttribute` method in the `HasTranslations` trait to handle array values for translatable attributes. 
**Motivation**
Previously, setting an array value for a translatable attribute would result in unexpected behavior, treating array indexes as locale keys. For example:
```php
$model->additional_info = ['Feature 1', 'Feature 2', 'Feature 3'];
```
Would store:
```json
{
"0": "Feature 1",
"1": "Feature 2",
"2": "Feature 3"
}
```
With this change, the array is now stored as a translation for the current locale:
```json
{
"en": ["Feature 1", "Feature 2", "Feature 3"]
}
```
Tests were added to verify the correct behavior of the `setAttribute` method with array values.
> Improve `setAttribute` to handle array list as value for translation

- src/HasTranslations.php
- tests/TranslatableTest.php
This PR introduces support for clearing translations by assigning an empty array to a translatable attribute.
- Modified the `setAttribute` method to handle empty arrays ([]) as a valid input for clearing translations, in addition to the existing behavior for non-list arrays.
- Added a test to ensure that assigning an empty array to a translatable attribute clears all translations for that attribute.
- It fixes #476 
Let me know if any additional updates or documentation are required!
> Support clearing translations using an empty array

- README.md
- src/HasTranslations.php
- tests/TestCase.php
- tests/TranslatableTest.php
Hi,
I added support for JSON fields, allowing nested keys to be translatable.
You can now specify key paths separated by ```->```, which is the same notation used in the framework for to set values for JSON keys
```php
$translatable = ['setting->footer->copyright'];
```
All methods for setting and retrieving translations will work with nested keys, but I've excluded the ability to pass nested keys to mutation methods.
Additionally, I modified the loading of translatable attribute casts to occur at initialization time rather than loading them on demand.
> Add support for nested key translations

- src/HasTranslations.php
- tests/TranslatableTest.php
This pull requests is originated from the conversation on #474 where @vencelkatai and i agreed on finding a way to have an implementation that satisfies our use cases and also keep the library consistent.
- Modified the `getTranslation` method to check if the raw attribute value is `null` using `self::getAttributeFromArray`. If the attribute is `null`, it will now treat the translation as `null` instead of falling back to an empty string.
Previously, `null` values in the database were treated inconsistently, being returned as empty strings in translations. This behavior could lead to unexpected results in applications that differentiate between `null` and empty strings. By aligning the translation output with the underlying database value, this change ensures more predictable and …
> Handle null database values as null in translations

- src/Facades/Translatable.php
- src/HasTranslations.php
- tests/TranslatableTest.php
Hi there,
When saving a translation with the `null` value an empty string will be returned when retrieving a translation. This behavior was discussed here https://github.com/spatie/laravel-translatable/issues/195 and was attempted to be fixed here https://github.com/spatie/laravel-translatable/pull/427 , but caused errors in projects using a string as the default value.
These errors were fixed in the PR https://github.com/spatie/laravel-translatable/pull/465  by adding `allowNullForTranslation` configuration  which is `false` by default.
But it still returns an empty string when retrieving a translation with a `null` value. This PR fixes this behavior and returns `null` instead of an empty string if `allowNullForTranslation` is `true`.
> Allow null value in translations if allowNullForTranslation is true
